#+TITLE: aru's XMobar config
#+DATE: April 08, 2021
#+OPTIONS: toc:3

#+begin_src text
                                /██                       /██      /████████
                               | ██                      | ██     |_____ ██/
  /██████  /██████ /██   /██   | ███████  /██████  /██████ ██   /██    /██/
 |____  ██/██__  █| ██  | ██/███ ██__  ██|____  ██/██____| ██  /██/   /██/
  /██████| ██  \__| ██  | ██/__/ ██  \ ██ /██████| ██    | ██████/   /██/
 /██__  █| ██     | ██  | ██   | ██  | ██/██__  █| ██    | ██_  ██  /██/
|  ██████| ██     |  ██████/   | ██  | █|  ██████|  ██████ ██ \  ██/████████
 \_______|__/      \______/    |__/  |__/\_______/\______|__/  \__|________/
#+end_src

Here is my XMobar config, and I also will guide you through the process of
installation.

* Installation

Here I will show you how to install xmobar, I will be doing it with cabal so if
you didn't follow my instructions to install XMonad, take look [[file:../../WindowManagers/xmonad/README.org::*Installing ghcup, cabal and more][here]] to know how
to install cabal.

** Installing xmobar

This is really easy, you just need to do a ~cabal install~, but in xmobar we can
add support for many things, like xft fonts and some widgets, so we will be
adding the flag ~--flags="all_extensions"~, so it will look like this:

#+begin_src shell
cabal install xmobar --flags="all_extensions"
#+end_src

And thats it, really easy.

**NOTE**: While cabal installs some alsa things, you may run into some problem,
you just need to ~export LANG=c~ and run again the
~cabal install xmobar --flags"all_extensions"~ command.

* Configuration

** xmobarrc

You will need a xmobarrc file (you can call it however you want) where you will
have your xmoabr configuration, if you have many monitors and want different
setups, make as many as needed. you can take a look at my current laptop +
external monitor setup.

** start xmobar from xmonad

Now that you configured xmobar, you will need to start from xmonad, so as you
can see in my [[file:../../../xmonad/xmonad.hs][xmonad config]] you will need to invoque it with a ~spawnPipe
"xmobar -x N path/to/xmobarrc"~, the ~-x N~ part is for telling xmobar in
which monitor to spawn.

You can then pass a logHook to xmobar for it to display some info, like
workspaces, current layout, window title, etc.
