#!/bin/bash

# .: ~ xmonad/build.sh file ~ :.
# by aru

SRC_DIR="$XDG_CONFIG_HOME/xmonad/"
EXE_NAME="aru-xmonad"

([[ -f "$SRC_DIR/build" ]] && cd "$SRC_DIR") || (echo "Set your \$SRC_DIR" && exit 1)

cabal install exe:"$EXE_NAME" \
    --enable-executable-stripping \
    --enable-optimization=2 \
    --installdir="$(dirname "$1")" \
    --overwrite-policy=always

[[ "$(basename "$1")" = "$EXE_NAME" ]] || ln -sf "$EXE_NAME" "$1"
